### ISSUE TITLE
Modify Parameters of Predeploy Contract to Match Integer Type

### ISSUE THREAD

**Issue by ferrell-code** [AcalaNetwork/Acala#2181]
Currently all predeploy contracts use `uint256` for function parameter, example: `getSwapTargetAmount(address[],uint256)`. 

Changing it to the matching type will ensure encoded value fits in the value used in Acala (all values are encoded as uint256) rather than allowing the possibility for contract to pass a too large number causing a revert. So for this example function would become `getSwapTargetAmount(address[],uint128)`

**Comment by xlc** [comment]
Note that we can't really modify interfaces of any already published predeploy contracts.
We can with careful migration to modify interface between precompile and predeploy by upgrading the predeploy contract code along with runtime upgrade.
But we maybe don't want to upgrade the contracts within upgrade because that will bloat wasm size.

**Comment by ermalkaleci** [comment]
most devs will just use `uint256` for balance or amount so they will expect to pass `uint256` as balance. So keeping balances and amount `uint256` and revert if balance cannot be converted into substrate balance might be fine. But we can make signed params or ratios to have same type.
