### ISSUE TITLE
Ledger Acala App not working with Acala Defi website anymore

### ISSUE THREAD

**Issue by sorinirimies** [AcalaNetwork/Acala#2603]
**Describe the bug**
Ledger Not working with Acala anymore
**Expected Behavior**
Acala app should work with my Ledger Nano X
**Current Behavior**
Acala App and website transactions don't work anymore.
**Steps to Reproduce**

1. Connect to Ledger through Talisman or Polkadot.js to the Acala website.
2. Swap Dot to LDOT, or try to stake or unstake (any operation)
3. I get TX not supported even though I use the latest Acala Ledger App and also the Acala site is updated
![image](https://github.com/AcalaNetwork/Acala/assets/17005155/9bfea6a0-1115-49ba-a914-e3ce34477735)

**Additional context**
Ledger Acala App version: v2.2110.0
Accoundtype: Crowdloan

**Comment by xlc** [comment]
The new Ledger app is under review by Ledger.
You may try it at https://hub.zondax.ch

**Comment by sorinirimies** [comment]
Awesome, great news, thx for the info.

**Comment by sorinirimies** [comment]
I tried it but it doesn't work, it doesn't want to install on my nano X.

**Comment by remi-parain** [comment]
Official available version  on Ledger Live  : Acala +  karura   firmware  2.2110.0 , from december  2022
Zondax available version : 
Acala :   3.2130.0 ( February) , 3.2160.0 (April) , 3.2180.0 (June) , 3.2180.1  (3 weeks ago) 
Karura  : 3.2130.0 (February)  , 3.2160.0 ( April).
No works done since April on Ledger-karura .... 

working status :
**latest Ledger** : Acala+Karura : stuck funds, can't do anything
l**atest Zondax** : 
- Acala:
  -  transfer  :ballot_box_with_check: 
  -  swap  :ballot_box_with_check: 
  -  bridge  :ballot_box_with_check: 
- Karura:
  - transfer  :ballot_box_with_check: 
  - swap  :ballot_box_with_check: 
  - bridge to Kusama   :negative_squared_cross_mark: : 
  
  @sorinirimies  it works on nano S+
  you can try to deploy the sourcecode using vscode and the ledger extension 
  Ledger doc: https://developers.ledger.com/docs/embedded-app/build-load/

**Comment by sorinirimies** [comment]
Ledger has now released a new Acala version 3.2180.2 which is now compatible with Acala Defi platform
![image](https://github.com/AcalaNetwork/Acala/assets/17005155/3d914afe-71a2-4452-884e-3bd4f4eb5220)

**Comment by sorinirimies** [comment]
Issue has been solved with latesst update
