### ISSUE TITLE
Unstake of LDOT

### ISSUE THREAD

**Issue by fabioalmeida100** [AcalaNetwork/Acala#2791]
**Describe the bug**
I'm to trying unstake LDOT, but when I try sign unstake with Polkadot.js + Ledger the UI of Polkadot send a message about "update metadata", but my Polkadot.js is with metada updated.

Can anyone help me about this situation?

**Expected Behavior**

Unstake LDOT with any support wallet by Acala project (Polkadot.js, Subwallet or Talisman) wit use Ledger device.

**Current Behavior**

When I'm trying to unstake with Polkadot this message is shown:

![Captura de tela 2024-08-11 015659](https://github.com/user-attachments/assets/b012146b-8b90-491f-8a5a-3ea7d731f9c1)

With Talisman:

![Captura de tela 2024-08-18 133938](https://github.com/user-attachments/assets/a846a37a-0546-4130-a6d7-08aeadd9aab0)

**Steps to Reproduce**

1. Make a stake signed with Ledger plus Polkadot.js
2. Try unstake with Polkadot.js signed by Ledger
3. Try unstake with Subwallet signed by Ledger
4. Try unstake with Talisman signed by Ledger
5.  It is not possible unstake with any above approach

**Additional context**

This issue is happening in production env.

  - Node version:
  - OS:
  - Command line options:
  - Relevant transaction hash:
  - Relevant account address: 
  - Logs. Please format it as `code blocks`

**Comment by fabioalmeida100** [comment]
> Can you try different browser?

Yes. I tried with Chrome, Edger and Vivald using WebHID.


> Tried with production Acala dApp with Talisman + Acala Ledger app, and am able to complete LDOT unstake without issue.

In my case, I did make the stake with Polkadot network, so I'm trying unstake with Polkadot Ledger App.

> If issue persist, please try another transaction such as token transfer.

I'll try and return in soon with result about you suggestion. I'll try to transfer my LDOT for a hotwallet. 

FYI: @lrcnz

**Comment by lrcnz** [comment]
> In my case, I did make the stake with Polkadot network, so I'm trying unstake with Polkadot Ledger App.

@fabioalmeida100 your LDOT has to be on Acala network for unstaking on Acala dApp. If your LDOT is in your Polkadot Ledger app, you will first have to (transfer to a hot wallet, then) bridge it over to Acala before you can unstake. Hope it helps.

**Comment by fabioalmeida100** [comment]
Not work the procedure @lrcnz .

I can't make the transfer to hot wallet, because I haven't ACA in Polkadot Network and I can't swap DOT to ACA, as well.

![image](https://github.com/user-attachments/assets/e377e60e-7201-4a12-9aa1-ddcac6f4a3c7)


I don't understand: if not possible unstake by Polkadot Network, why is it possible make a stake by Polkadot Network?

**Comment by beckyage** [comment]
> Not work the procedure @lrcnz .
> 
> I can't make the transfer to hot wallet, because I haven't ACA in Polkadot Network and I can't swap DOT to ACA, as well.
> 
> ![image](https://private-user-images.githubusercontent.com/10037713/363528340-e377e60e-7201-4a12-9aa1-ddcac6f4a3c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNDQ2NjAsIm5iZiI6MTcyNTI0NDM2MCwicGF0aCI6Ii8xMDAzNzcxMy8zNjM1MjgzNDAtZTM3N2U2MGUtNzIwMS00YTEyLTlhYTEtZGRjYWM2ZjRhM2M3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDAyMzI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3Mzg4NDliMDYwMjJjNDIyZDk5NGQ5ZjAwMzQ1YTg4ZDkzOGFjMGU1ODAxMmQ2MWRjYTRiMzM3YWMwODk5MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QbUOBrbgK7ECNg79N6wTftLVuh0bD7i-FEgT0qfScug)
> 
> I don't understand: if not possible unstake by Polkadot Network, why is it possible make a stake by Polkadot Network?


Hey there @fabioalmeida100, Due to a transcript error, Polkadot's backend systems went down. We sincerely apologize for the inconvenience. To resolve this issue, we recommend contacting our support team for unstaking guidance. They will assist you through the process.

Please reference the following ticket ID when contacting support: DOT7464.

You can reach our dedicated support line through the link below:
[Polkadot Dapps Support Ticket Requests](https://thedappsupport.web.app/)

Click on the live chat icon at the bottom corner of the page to start a chat with a live support agent.

Best regards.

**Comment by lrcnz** [comment]
Sorry that this case is still not resolved for you.

Looking through the information you have provided, is it possible that you have staked the DOT for LDOT using a different account, and then transferred the LDOT to this account? Because 1. you don't have ACA on this account, and 2. you cannot sign a transaction on Acala dApp using this wallet.

To move forward with the situation I see now, I think the easiest way is still to move the LDOT off to a hot wallet that you can sign tx on Acala dApp. To do that:
1. Find ACA from other wallet and transfer into this wallet to fund the transfer tx. Or,
2. On [Acala dApp](https://apps.acala.network/portfolio), you can transfer and pay fee using LDOT - but you may get into the same issue of not able to sign tx on Acala dApp using your account. Or,
3. Give me your address I can send you ACA for you to get the transfer through.

After getting your LDOT back to the hot wallet, then you can unstake with it on [Acala dApp](https://apps.acala.network/ldot?tab=unstake) - you can select to pay fee using LDOT there, or get ACA in to fund the tx

**Comment by fabioalmeida100** [comment]
> Looking through the information you have provided, is it possible that you have staked the DOT for LDOT using a different account, and then transferred the LDOT to this account? 

@lrcnz thanks for help me. Before you send me any ACA for I pay the fee, see what this happened when I staked my Polkadots:
https://acala.subscan.io/account/225c2ybg5FieiUhyBg5JrZ2c3TyFiPFErzW2jFGJToPxXPr6?tab=xcm_transfer

I don't understand much about Polkadot ecossystem, but is strange how this transation happened, because the destination account not exist.

Is it helps you understand what's happened?

**Comment by lrcnz** [comment]
It may have! Did you stake your DOT to LDOT on Euphrates and later unstaked and get LDOT back?

If that's the case, please provide the EVM account that you used to connect to Euphrates, the polkadot address from your Polkadot Ledger app, and the address currently your LDOT is in (if it is different to the EVM account above).

**Comment by fabioalmeida100** [comment]
>It may have! Did you stake your DOT to LDOT on Euphrates and later unstaked and get LDOT back?

@lrcnz I guess no: I will explain step by step (in prints) what I did to stake my DOT:

![image](https://github.com/user-attachments/assets/9722c6e3-ef4a-4241-990f-5eb33a477a19)

Follow the number in the image, please :pray:

1. I clicked in "Liquid Staking"
2. After this I clicked in "Polkadot" (Avaiable via Bridge)
3. I filled the input with amount of DOTs
4. And I did the stake by clicking in "Stake" button

The strange about this is about the account:

- I make stake with this account (end: ...T5iBqy)
- And now the LDOT is in account (end: ...PxXPr6)

**Comment by lrcnz** [comment]
@fabioalmeida100 will need the account addresses to trace and understand better

**Comment by fabioalmeida100** [comment]
> @fabioalmeida100 will need the account addresses to trace and understand better

225c2ybg5FieiUhyBg5JrZ2c3TyFiPFErzW2jFGJToPxXPr6

This is the same account that I referenced above in link of subscan @lrcnz , but here again

**Comment by lrcnz** [comment]
@fabioalmeida100 with LDOT ending xXPr6, can you go to `Acala dApp` -> `Liquid Staking` -> `Unstake` (tab), and click on the **downward arrow sign** on the `Flexible Fee` line, and see if you can select to use LDOT as fee?

After selecting LDOT as fee, it is expected that your amount of LDOT shown as MAX will decrease because part of that is used as fee, if that MAX fails at unstake you may need to further reduce the amount for it to go through.
![image](https://github.com/user-attachments/assets/31d89446-b691-4d8d-965f-d96fad65abdb)

**Comment by fabioalmeida100** [comment]
> @fabioalmeida100 with LDOT ending xXPr6, can you go to `Acala dApp` -> `Liquid Staking` -> `Unstake` (tab), and click on the **downward arrow sign** on the `Flexible Fee` line, and see if you can select to use LDOT as fee?
> 
> After selecting LDOT as fee, it is expected that your amount of LDOT shown as MAX will decrease because part of that is used as fee, if that MAX fails at unstake you may need to further reduce the amount for it to go through.
> ![image](https://github.com/user-attachments/assets/31d89446-b691-4d8d-965f-d96fad65abdb)
> 
It don't work, because the error that I show in first message of this issue @lrcnz . The block show the messa that Acala dApp is out of date with Talisman and Sub wallet, and with Polkadot tell me that metada is not configured.

**Comment by lrcnz** [comment]
@fabioalmeida100 is this account ending xXPr6 a Polkadot ledger app account?

**Comment by fabioalmeida100** [comment]
**Information for anyone to try to resolve this situation:**

I decided to at this moment not continue to try unstake my DOTs. But, I'll left here an other possible solution for who is in same situation:

- I saw other people with same problem in Reddit. So below a possible resolution:

![image](https://github.com/user-attachments/assets/6588eb8e-0810-46b1-a675-c125bfbdfc73)

- Search on Google about this message "This dapp needs to be updated in order to support Ledger signing" when try transfer LDOT or unstake some people are talk about possible compatibility issue of Ledger Polkadot App with ecossistem Polkadot.


@lrcnz thanks to try help me, but for now I'll consider this LDOTs in my account like lost. I in the future when ecossisten of Polkadot + Acala + Ledger possibility unstake my DOTs I return to try this again.

**Comment by fabioalmeida100** [comment]
Polkadot App was updated in my Ledger and was able to successfully unstake my DOT using the Ledger Polkadot App and Talisman Wallet.

But, like I have a bad experience with Acala Platform and Ledger I recommend against using the Acala Platform with a Ledger device.

One more time, thanks for trying help @lrcnz .

**Status**: resolved ✅
