### ISSUE TITLE
Use native decimals

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/Acala#761]
Previously we normalize all tokens to be 18 decimals. But this have become infeasible when dealing with crosschain tokens because we have no idea about their decimals.

Changes:

- [x] Update module-prices to convert the price with decimal consideration @wangjj9219 
- [x] Update related runtime configs and airdrop value @wangjj9219 
- [x] Remove decimal conversion code in xtokens @shaunxw 
- [x] Make sure we cannot convert Balance to FixedU128 directly without some decimal logic @wangjj9219 
- [x] Review all multiplication & division code @wangjj9219 
- [ ] Update frontend @qiuhao951 @RomeroYang 
- [ ] In future implement and use FixedU256

**Comment by wangjj9219** [comment]
@qwer951123 
I adjust the calculation for the initial share of LPToken: always use the big number divide by the small number in order to minimize the loss, and the decimals of lptoken cannot be determined in advance. Refer to the practice of Maker, The front-end can use the max decimals between symbol1 and sybmol2 to handle display,  the decimals may be larger in this way but it's still within the acceptable range.
